version: "3"

services:
  app:
    image: nemirlev/zenexport:v1.4.2
    env_file: .env
    depends_on:
      clickhouse:
        condition: service_healthy

  clickhouse:
    image: yandex/clickhouse-server
    env_file: .env
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
        - ./clickhouse:/docker-entrypoint-initdb.d
        - clickhouse:/var/lib/clickhouse
    healthcheck:
      test: wget --no-verbose --tries=1 http://localhost:8123 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - ./grafana:/etc/grafana/provisioning
      - grafana:/var/lib/grafana

volumes:
    clickhouse:
        driver: local
    grafana:
        driver: local