{
 "title": "Бюджет",
 "description": "Панель со своим бюджетом",
 "time": { "from": "now/fy", "to": "now/fy" },
 "panels": [
  {
   "title": "Баланс",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    SUM(balance) AS \"Текущий Баланс\"\nFROM \"zenmoney\".\"account\"\nWHERE type NOT IN ('loan', 'debt') AND archive != 1",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Кредиты",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    SUM(balance) AS \"Общий Баланс Кредитов\"\nFROM \"zenmoney\".\"account\"\nWHERE type = 'loan' AND archive != 1",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Баланс-Кредит",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    SUM(balance) AS \"Баланс за Вычетом Кредитов\"\nFROM \"zenmoney\".\"account\"\nWHERE archive != 1",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Инструменты",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    i.title AS Instrument,\n    sum(t.income) as TotalIncome,\n    sum(t.outcome) as TotalOutcome\nFROM transaction t\nLEFT JOIN instrument i ON t.income_instrument = i.id OR t.outcome_instrument = i.id\nWHERE t.deleted = false\nGROUP BY i.title\nORDER BY i.title",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Мои счета",
   "type": "barchart",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n    title AS \"Счет\", \n    CASE type \n        WHEN 'ccard' THEN 'банковская карта'\n        WHEN 'checking' THEN 'банковский счет'\n        WHEN 'loan' THEN 'кредит'\n        WHEN 'deposit' THEN 'депозит'\n        WHEN 'cash' THEN 'наличные'\n        WHEN 'debt' THEN 'долги'\n        ELSE type\n    END AS \"Тип\",\n    balance AS \"Баланс\"\nFROM \"zenmoney\".\"account\"\nWHERE archive != 1\nORDER BY \"Тип\", \"Баланс\" DESC\n",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Расходы и доходы",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfMonth(toDate(date)) AS Month,\n    'Income' AS Type,\n    sum(income) AS Total\nFROM transaction\nWHERE income > 0 \n      AND deleted = 0 \n      AND outcome_account = income_account\n      AND $__timeFilter(toDateTime(toDate(date)))\nGROUP BY Month",
     "selectedFormat": 4
    },
    {
     "rawSql": "SELECT\n    toStartOfMonth(toDate(date)) AS Month,\n    'Outcome' AS Type,\n    sum(outcome) AS Total\nFROM transaction\nWHERE outcome > 0 \n      AND deleted = 0 \n      AND outcome_account = income_account\n      AND $__timeFilter(toDateTime(toDate(date)))\nGROUP BY Month",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Расходы по категориям",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    if(t1.title IS NULL, 'Без категории', t1.title) AS Category,\n    sum(outcome) AS TotalOutcome\nFROM transaction\nARRAY JOIN tag AS tag_id\nLEFT JOIN tag AS t1 ON t1.id = tag_id\nWHERE outcome > 0 \n      AND deleted = 0 \n      AND $__timeFilter(toDateTime(toDate(date)))\n      AND t1.parent IS NULL\nGROUP BY Category\nORDER BY TotalOutcome DESC\n",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Расходы по категориям",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 14, "x": 10, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "rawSql": "SELECT\n    if(t1.title IS NULL, 'Без категории', t1.title) AS Category,\n    sum(outcome) AS TotalOutcome\nFROM transaction\nARRAY JOIN tag AS tag_id\nLEFT JOIN tag AS t1 ON t1.id = tag_id\nWHERE outcome > 0 AND deleted = 0 AND $__timeFilter(toDateTime(toDate(date))) AND t1.parent IS NULL\nGROUP BY Category\nORDER BY TotalOutcome DESC",
     "selectedFormat": 4
    }
   ]
  }
 ]
}