apiVersion: 1
datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    is_default: true
    jsonData:
      defaultDatabase: $CLICKHOUSE_DB
      port: 9000
      server: clickhouse
      username: $CLICKHOUSE_USER
      tlsSkipVerify: false
    secureJsonData:
      password: $CLICKHOUSE_PASSWORD